import { BadRequestException, Injectable } from '@nestjs/common';
import { promises as dns } from 'dns';
import { DnsProviderType, Prisma } from '@prisma/client';
import { ProviderLogsService } from './provider-logs.service';

export interface DnsRecordInput {
  type: string;
  name: string;
  value: string;
  ttl?: number;
  priority?: number;
}

export interface DnsRecordRequirement {
  key: 'spf' | 'dkim' | 'dmarc' | 'mx' | 'tracking';
  label: string;
  type: string;
  host: string;
  value: string;
  priority?: number | null;
  status: string;
  required: boolean;
  instructions: string;
}

export interface DomainDnsRecordConfig {
  domain: string;
  spfStatus?: string;
  dkimStatus?: string;
  dmarcStatus?: string;
  mxStatus?: string;
  dkimType?: string | null;
  dkimHost?: string | null;
  dkimValue?: string | null;
  trackingDomain?: string | null;
  trackingCnameValue?: string | null;
  trackingDomainActive?: boolean;
}

export interface DomainVerificationConfig {
  dkimType?: string | null;
  dkimHost?: string | null;
  dkimValue?: string | null;
  trackingDomain?: string | null;
  trackingCnameValue?: string | null;
}

@Injectable()
export class DnsProviderService {
  constructor(private readonly logs: ProviderLogsService) {}

  async createRecords(input: {
    tenantId: string;
    provider: DnsProviderType;
    domain: string;
    zoneId?: string | null;
    apiKey: string;
    records: DnsRecordInput[];
  }) {
    if (input.provider === DnsProviderType.cloudflare) {
      return this.createCloudflareRecords(input);
    }
    return this.createNamecheapRecords(input);
  }

  requiredRecords(input: DomainDnsRecordConfig): DnsRecordRequirement[] {
    const trackingHost = input.trackingDomain || `track.${input.domain}`;
    const records: DnsRecordRequirement[] = [
      {
        key: 'spf',
        label: 'SPF Record',
        type: 'TXT',
        host: input.domain,
        value: 'v=spf1 include:_spf.google.com include:sendgrid.net ~all',
        priority: null,
        status: input.spfStatus ?? 'not_set',
        required: true,
        instructions: 'Authorizes Google Workspace and SendGrid to send mail for this domain.',
      },
      {
        key: 'dkim',
        label: 'DKIM Record',
        type: (input.dkimType || 'TXT').toUpperCase(),
        host: input.dkimHost || '',
        value: input.dkimValue || '',
        priority: null,
        status: input.dkimStatus ?? 'not_set',
        required: true,
        instructions: 'Paste the exact DKIM host and value generated by Google Workspace, Microsoft 365, SendGrid, or your email provider.',
      },
      {
        key: 'dmarc',
        label: 'DMARC Record',
        type: 'TXT',
        host: `_dmarc.${input.domain}`,
        value: `v=DMARC1; p=quarantine; rua=mailto:dmarc@${input.domain}`,
        priority: null,
        status: input.dmarcStatus ?? 'not_set',
        required: true,
        instructions: 'Sets domain alignment policy and sends aggregate DMARC reports.',
      },
      {
        key: 'mx',
        label: 'MX Record',
        type: 'MX',
        host: input.domain,
        value: 'aspmx.l.google.com',
        priority: 1,
        status: input.mxStatus ?? 'not_set',
        required: true,
        instructions: 'Routes mailbox delivery for the sending domain.',
      },
    ];

    if (input.trackingDomain || input.trackingCnameValue) {
      records.push({
        key: 'tracking',
        label: 'Tracking CNAME',
        type: 'CNAME',
        host: trackingHost,
        value: input.trackingCnameValue || 'sendgrid.net',
        priority: null,
        status: input.trackingDomainActive ? 'verified' : 'not_set',
        required: false,
        instructions: 'Connects a branded tracking domain for opens and clicks.',
      });
    }

    return records;
  }

  async verify(domain: string, config: DomainVerificationConfig = {}) {
    const [txt, mx, tracking] = await Promise.allSettled([
      dns.resolveTxt(domain),
      dns.resolveMx(domain),
      config.trackingDomain ? dns.resolveCname(config.trackingDomain) : Promise.resolve([]),
    ]);
    const txtRows = txt.status === 'fulfilled' ? txt.value.map((row) => row.join('')) : [];
    const txtValues = txtRows.join(' ');
    const mxValues = mx.status === 'fulfilled' ? mx.value : [];
    const trackingValues = tracking.status === 'fulfilled' ? tracking.value : [];

    return {
      spfValid: txtValues.includes('v=spf1'),
      dkimValid: await this.hasDkim(config),
      dmarcValid: await this.hasDmarc(domain),
      mxValid: mxValues.length > 0,
      trackingValid: this.matchesCname(trackingValues, config.trackingCnameValue),
    };
  }

  private async hasDkim(config: DomainVerificationConfig) {
    if (!config.dkimHost || !config.dkimValue) return false;
    const recordType = (config.dkimType || 'TXT').toUpperCase();

    if (recordType === 'CNAME') {
      const values = await dns.resolveCname(config.dkimHost).catch(() => []);
      return this.matchesCname(values, config.dkimValue);
    }

    const values = await dns.resolveTxt(config.dkimHost).catch(() => []);
    const expected = this.normalizeTxt(config.dkimValue);
    return values.some((row) => this.normalizeTxt(row.join('')) === expected);
  }

  private async hasDmarc(domain: string) {
    const result = await dns.resolveTxt(`_dmarc.${domain}`).catch(() => []);
    return result.flat().join(' ').includes('v=DMARC1');
  }

  private matchesCname(values: string[], expected?: string | null) {
    if (!values.length) return false;
    if (!expected) return true;
    const normalizedExpected = this.normalizeDnsName(expected);
    return values.some((value) => this.normalizeDnsName(value) === normalizedExpected);
  }

  private normalizeDnsName(value: string) {
    return value.trim().toLowerCase().replace(/\.$/, '');
  }

  private normalizeTxt(value: string) {
    return value.trim().replace(/^"|"$/g, '').replace(/\s+/g, '');
  }

  private async createCloudflareRecords(input: {
    tenantId: string;
    domain: string;
    zoneId?: string | null;
    apiKey: string;
    records: DnsRecordInput[];
  }) {
    if (!input.zoneId) throw new BadRequestException('Cloudflare zone id is required');
    const created: Array<{ name: string; id?: string }> = [];
    for (const record of input.records) {
      const response = await fetch(`https://api.cloudflare.com/client/v4/zones/${input.zoneId}/dns_records`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${input.apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: record.type,
          name: record.name,
          content: record.value,
          ttl: record.ttl ?? 1,
          priority: record.priority,
        }),
      });
      const body = await response.json().catch(() => ({}));
      await this.logs.create({
        tenantId: input.tenantId,
        provider: 'cloudflare',
        operation: 'dns_record_create',
        status: response.ok ? 'success' : 'failed',
        request: record as unknown as Prisma.InputJsonValue,
        response: body,
        error: response.ok ? undefined : JSON.stringify(body),
      });
      if (!response.ok) throw new BadRequestException(`Cloudflare DNS record failed for ${record.name}`);
      created.push({ name: record.name, id: body?.result?.id });
    }
    return created;
  }

  private async createNamecheapRecords(input: {
    tenantId: string;
    domain: string;
    apiKey: string;
    records: DnsRecordInput[];
  }) {
    await this.logs.create({
      tenantId: input.tenantId,
      provider: 'namecheap',
      operation: 'dns_record_create',
      status: 'pending',
      request: { domain: input.domain, records: input.records.map((record) => ({ ...record, value: '[redacted]' })) },
      response: { message: 'Namecheap API credentials require ApiUser, UserName, ClientIp, and domain SLD/TLD mapping.' },
    });
    throw new BadRequestException('Namecheap DNS automation requires full Namecheap account API metadata');
  }

  async createCloudflareZone(input: { tenantId: string; domain: string; apiKey: string }): Promise<{ zoneId: string; nameservers: string[] }> {
    const response = await fetch('https://api.cloudflare.com/client/v4/zones', {
      method: 'POST',
      headers: { Authorization: `Bearer ${input.apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: input.domain, jump_start: true }),
    });
    const body = await response.json().catch(() => ({} as any));
    await this.logs.create({
      tenantId: input.tenantId, provider: 'cloudflare', operation: 'zone_create',
      status: response.ok ? 'success' : 'failed',
      request: { domain: input.domain }, response: body,
      error: response.ok ? undefined : JSON.stringify(body),
    });
    if (!response.ok) throw new BadRequestException(`Failed to create Cloudflare zone for ${input.domain}: ${body?.errors?.[0]?.message ?? 'Unknown error'}`);
    return { zoneId: body.result.id, nameservers: body.result.name_servers };
  }

  async getCloudflareZone(apiKey: string, domain: string): Promise<{ zoneId: string; nameservers: string[] } | null> {
    const response = await fetch(`https://api.cloudflare.com/client/v4/zones?name=${encodeURIComponent(domain)}`, {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    const body = await response.json().catch(() => ({} as any));
    if (!response.ok || !body.result?.length) return null;
    return { zoneId: body.result[0].id, nameservers: body.result[0].name_servers };
  }
}
